name: Photoreality
favicon: null
layout_spectrum: 0.54811
typography_spectrum: 0.83761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9eb936'
    - '#ff7eff'
    - '#1f241e'
    - '#ff23b5'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
