name: Photoreality
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9eb936'
    - '#ff7eff'
    - '#1f241e'
    - '#ff23b5'
  brandStrength: 0.19574432540684938
  lightness: 0.4508943469263613
  saturation: 0.4555518478155136
  rhythmicContrast: 0.7112316489219666
purpose: []
